<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>IBM-Details</title>

<!-- css -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="mystyle.css" rel="stylesheet" type="text/css"/>

</head>

<body>

<style>
 body
{ 
	
}

.primary-background {
	background: #ff5252!important;
}


*{
  margin: 0;
  padding: 0;
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}

h1{
  font-size: 2.5rem;
  font-family: 'Montserrat';
  font-weight: normal;
  color: #444;
  text-align: center;
  margin: 2rem 0;
}

.wrapper{
  width: 90%;
  margin: 0 auto;
  max-width: 80rem;
}
           
        </style>

<!-- navbar -->
<%@include file="../common/normal_navbar.jsp" %>

 <main class="d-flex align-items-center" style="height: 380vh">
  <div class="container">
    

  <div class="card border-success mb-50" style="max-width: 100rem;">
  <div class="card-header bg-transparent border-dark" ><h5>ABOUT IBM</h5></div>
  <div class="card-body text-dark">
  
  <p class="card-text">International Business Machines Corporation (IBM) is an American multinational information technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed "International Business Machines" in 1924. IBM is incorporated in New York</p>
  <br><p class="card-text">IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most U.S. patents generated by a business (as of 2019) for 26 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM).</p>



<br>IBM employees have been awarded five Nobel Prizes, six Turing Awards, ten National Medals of Technology (USA) and five National Medals of Science (USA). IBM has appointed Ginni Rometty as chief executive officer.

  
  <h5 class="card-title">OVERVIEW</h5>
    <p class="card-text">In case of job recruitment, selection is the process to choose potential working persons for a company or organization.It directly affects the overall productivity of an organization. A right selection may increase the overall performance of a company & a wrong one may lead to material and financial loss. A perfect selection process can help to pick the most eligible candidates amongst all applicants.</p>
    <br>IBM has two different profiles GBS i.e. IBM Global Business Solutions and GTS i.e. IBM Global Technological Solutions. It has both on campus and off campus drive. 
    
    <h5 class="card-title">HIRING CRITERIA</h5>
     <h5 class="card-title">Graduation Criteria</h5>
    <p class="card-text">Graduation Criteria
Only full-time courses will be considered (Part Time/Correspondence courses will not be considered).
<br>1) B.E / B.Tech  in any discipline (CSE/ECE/IT/EEE/TELECOM/EI ).
<br>2) Engineering candidates who have passed out in the year 2018 & 2019 are eligible to apply.
<br>3) M.Sc graduates in Computer Science &  Information technology can apply.
<br>4) MCA graduates are also eligible to apply.
<br>5) The graduation should be a Full-Time course recognized by Central/State government of India.
<br>Please note that a candidate is expected to have good communication & interpersonal skills, along with a good command on technical subjects.</p>
    .
 <h5 class="card-title">Academic Criteria</h5>

1) A candidate must have more than 65% marks in 10th and 12th (or diploma).
<br>2) A candidate must have a minimum of 65% marks in graduation.
<br>3) A maximum gap of 1 year is permissible after HSC(12th) and not after SSC(10th) or in between semesters of graduation.
<br>4) A candidate should not have any pending backlogs at the time of appearing for IBM selection process.
<br>5) Please note sometimes IBM has a minimum 70% marks requirement across the entire education but this selection criterion varies from college to college.

 
 <h5 class="card-title">IBM policies</h5>
    <p class="card-text">1) If a candidate has attended an interview within the past 6 months from the date of new application, then he/she is ineligible to apply.
<br>2) If a candidate has been rejected by IBM in an interview, then the candidate is ineligible to apply again for a period of 6 months after the interview.
<br>3) If for some reason IBM has terminated the candidate's application, then the candidate is ineligible to apply. 
<br>4) If for any reason a candidate after applying in IBM, misses the opportunity to give the interview then the candidate holds the right to apply again and can attend the selection process.
<br>5) The candidate should be an Indian citizen however, Bhutan & Nepal students can also work in India without obtaining any work-related VISA.  All other foreign nationals are required to have a work visa or an OCI / PIO card to work in India. Bhutan & Nepal nationals would also need to submit a Citizenship certificate or a Govt. ID Card in the absence of other documents (PIO/OCI/Work permit/passport).
    </p>
 
 <h5 class="card-title">Documents required</h5>
    <p class="card-text">1) All original mark sheets related to SSC (10th), Intermediate(12th) and Graduation are required to be produced at the time of interview. Also, please carry a copy of a set of all documents at the time of interview.
<br>2) A copy of candidate's updated resume.
<br>3) Passport size photographs.
<br>4) An original identification proof issued by the government of India (Aadhar Card, Pan Card, Voter id, Passport etc.)
    
  <h5 class="card-title">SELECTION PROCESS</h5>
    <p class="card-text">IBM has a simple process of recruitment online test / written round and the interview round.
 
<br><b>Written Round :</b>
The Written round consists of two parts namely Number Series and General Aptitude Test and English Assessment Test. For Number Series and General Aptitude Test. And for the English Assessment Test, total time duration is 20 minutes. There is no timer for each question as in the 1st round. Both are objective tests.
    
 
  <h4 class="card-title">INTERVIEW</h4>
    <p class="card-text"><b>Technical Interview</b>
        <br>The questions are entirely based on the technologies mentioned in the Job Description. The candidate might be asked to write a piece of code, or an algorithm to demonstrate the knowledge required in the particular field. Questions might also be based on the tools and technologies used in past projects.
        
 <br><b>
 HR Interview</b>
<br>It helps to determine a candidate's personality. Questions can be of wide range starting from your introduction, Qualification, Experience, Industry specific experience, Courses done, your strengths and weaknesses, salary expectations, friends, family etc. . Be ready to take questions based on your CV - internships, projects, volunteerships and co-curricular activities.
    
    </p>
   <br> Never say No when interviewer asks - Do you have any questions for me? Ask about company's culture and progress associated or something you wnat to know.
    
    <h4 class="card-title">PATTERN</h4>
    <p class="card-text">Topics	Questions	Time(mins)
Number Series	18	40
Quantitaive Aptitude	18	40
Business Communication Test 	22	20
Total	58	100
 
    <br>1.There is no negative marking.
    <br>2.There is  over all Cut-off.
    

<h4 class="card-title">SYLLABUS</h4>
    <p class="card-text">Quantitaive	Business Comm. Test	Number Series
<br>•	Profit and Loss
<br>•	Ratios and Proportions
•	Percentages
•	Probability
•	Speed Time and Distance
•	Permutation and Combination
•	Number System
•	Simplification and Approximation
•	Indices and Surds
•	Mensuration
•	Permutations and Combinations
•	Time and Work
•	Time and Distance
•	Problems on L.C.M and H.C.F
•	Simple Interest
•	Areas
•	Problems on Trains	•	Active/Passive voice
•	Synonyms and Antonyms
•	Fill in the Blanks
•	Reading comprehension
•	Synonyms
•	Antonyms
•	Sentence completion
•	Sentence correction
•	Vocabulary
•	Sentence ordering	
    
    </p>
    
    
    
    
     <br>
     
     <form method="get" action="https://www.ibm.com/">
         <button  class="btn  btn-outline-success btn-lg">GO TO OFFICIAL SITE</button>
    
    </form>
 </div>
 </main>




<!-- javascripts -->
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="js/myjs.js" type="text/javascript"></script>

<%@ include file="../common/footer.jsp" %>


</body>
</html>